feat: Add Prettier to repo
Anthrocon/www pull request #3
Opened 2023-11-04 18:57 UTC by takouhai

Adding [Prettier](https://prettier.io/) with a [Go template plugin](https://github.com/NiklasPor/prettier-plugin-go-template) to help us with compatibility. Added documentation on how to run it, too.

2023-11-05 11:04 UTC, RandornCanis requested changes

2023-11-05 11:04 UTC, RandornCanis commented on package.json
> +  "description": "anthrocon's website",
Must describe the package, not repository.

This avoids licensing issues.

2023-11-05 18:58 UTC, takouhai commented on .gitignore
> +
Funny, this is from the [GitHub community suggestions](https://github.com/github/gitignore/blob/main/community/Golang/Hugo.gitignore). Maybe I should throw up a better PR...

2023-11-06 09:14 UTC, RandornCanis approved these changes

2023-11-06 09:15 UTC, merged